#!/bin/bash

# Shorthand script which takes an IPv4 address and calls
# Firewalld to block it after which reloads the firewall.

# Written by xyz666

PATTERN="[\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}]"

# Check if the entered data is a valid IPv4 address
if [[ $@ =~ $PATTERN ]]
then    
    echo "Blocking $@ IP address!"

    firewall-cmd --add-rich-rule="rule family='ipv4' source address='$@' drop" --permanent
else
    echo "This is not an IPv4 address!"
    exit 1
fi    
# Optional; Enable it ONLY if you have a powerfull system
# or only a few entries in the firewall system
#echo "Reloading Firewall"
#firewall-cmd --reload
